//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGaming.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenGaming.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #version 330 core
        ///
        ///in vec3 vertexWorldPosition;
        ///in vec3 vertexNormal;
        ///in vec2 vertexUV;
        ///in vec3 vertexColor;
        ///
        ///uniform float ambient;
        ///uniform float diffuse;
        ///uniform float specular;
        ///
        ///uniform sampler2D colorTexture;
        ///uniform sampler2D ambientTexture;
        ///uniform sampler2D diffuseTexture;
        ///uniform sampler2D specularTexture;
        ///
        ///out vec4 fragmentColor;
        ///
        ///void main()
        ///{
        ///    vec4 color = vec4(vertexColor, 1);
        ///    vec4 ambientColor = color * ambient;
        ///} 的本地化字符串。
        /// </summary>
        internal static string StandardFragmentShader {
            get {
                return ResourceManager.GetString("StandardFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #version 330 core
        ///
        ///layout(location = 0) in vec3 position;
        ///layout(location = 1) in vec3 normal;
        ///layout(location = 2) in vec2 uv;
        ///
        ///uniform mat4 modelMatrix;
        ///uniform mat4 viewMatrix;
        ///uniform mat4 projectionMatrix;
        ///
        ///uniform vec3 color;
        ///uniform sampler2D displacementTexture;
        ///
        ///out vec3 vertexWorldPosition;
        ///out vec3 vertexNormal;
        ///out vec2 vertexUV;
        ///out vec3 vertexColor;
        ///
        ///void main()
        ///{
        ///    vec4 finalModelPosition = vec4(position, 1) + texture2D(displacementTexture, uv);
        ///    vec4 finalPosition = [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StandardVertexShader {
            get {
                return ResourceManager.GetString("StandardVertexShader", resourceCulture);
            }
        }
    }
}
